services:
  - type: web
    name: fastapi-render-demo
    env: python
    region: oregon  # or any region you like
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    # Optional: attach a persistent disk if you want the SQLite file to survive restarts.
    # For free web services, disks may not be available; prefer Postgres for persistence.
    # disk:
    #   name: data-disk
    #   mountPath: /opt/render/project/src
    #   sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # If you create a Render Postgres, set this to its connection string:
      # - key: DATABASE_URL
      #   sync: false  # you'll fill it in the dashboard
